site_name: PFE_24.2_8001
theme:
  name: null
  custom_dir: 'cinder'
  locale: pt_BR
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - html
    - css
    - javascript
repo_url: "https://github.com/jonh-carvalho/PFE_24.2_8001"